language: node_js

node_js:
  - 14.17.1

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: false
  directories:
    - "~/.pnpm-store"
    - ~/.cache

before_install:
  - curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store

install:
  - pnpm install

script:
  # Build
  - pnpm run -r build
  # Check
  - pnpm run check
